import { Investment } from './investment';
import { Forum } from './forum';
import { Team } from './team';

export interface RealState {
  property: string;
  builder: string;
  offerVideo: string;
  logo: string;
  logoDocUrl: string;
  banner: string;
  bannerDocUrl: string;
  duration: number;
  annualMaxProfitability: number;
  annualMinProfitability: number;
  minimalProfitability: number;
  projectedMaxProfitability: number;
  projectedMinProfitability: number;
  returnTimeInMonths: number;
  description: string;
  business: string;
  achievements: string;
  location: string;
  locationLink: string;
  roundDoc: string;
  builderDoc: string;
  propertyDoc: string;
  viabilityDoc: string;
  taxationDoc: string;
  legalDoc: string;
  roundDocUrl: string;
  builderDocUrl: string;
  propertyDocUrl: string;
  viabilityDocUrl: string;
  taxationDocUrl: string;
  legalDocUrl: string;
  totalApartments: number;
  availableApartments: number;
  quotas: number;
  quotaValue: number;
  riskiness: string;
  posts: Forum;
  investments: Investment;
  executiveTeam: Team;
  resume: Investment;
  startedAt?: string;
  id: number;
  status: string;
}
